module.exports = [
    "Aleppo",
    "Anaheim",
    "Ancho",
    "Banana pepper",
    "Bell pepper",
    "Bird's eye",
    "Cascabel",
    "Cayenne",
    "Chilaca",
    "Chungyang",
    "Cubanelle",
    "Chile de arbol",
    "Dundicut",
    "Facing heaven",
    "Fresno",
    "Friggitello",
    "Guajillo",
    "Hungarian wax",
    "Jalapeño",
    "Medusa",
    "Mulato",
    "New Mexico",
    "Padrón",
    "Pasilla",
    "Peter",
    "Pimento",
    "Poblano",
    "Santa Fe Grande",
    "Serrano",
    "Shishito"
]